/**
 * Export analysis data as JSON file
 */

export function exportJson(
  data,
  filename = "recycling-report"
) {
  try {
    // FORMAT JSON
    const jsonString = JSON.stringify(
      data,
      null,
      2
    );

    // CREATE BLOB
    const blob = new Blob(
      [jsonString],
      {
        type: "application/json",
      }
    );

    // CREATE DOWNLOAD URL
    const url =
      window.URL.createObjectURL(blob);

    // CREATE LINK
    const link =
      document.createElement("a");

    link.href = url;

    link.download = `${filename}.json`;

    // TRIGGER DOWNLOAD
    document.body.appendChild(link);

    link.click();

    // CLEANUP
    document.body.removeChild(link);

    window.URL.revokeObjectURL(url);

    return true;

  } catch (error) {
    console.error(
      "JSON export failed:",
      error
    );

    return false;
  }
}

/**
 * Export analysis data as formatted text
 */

export function exportTextReport(
  data,
  filename = "recycling-summary"
) {
  try {
    const report = `
RECYCLEVISION ANALYSIS REPORT
====================================

Bottle Count:
${data.bottle_count}

PET Percentage:
${data.pet_percentage}%

Non-PET Percentage:
${data.non_pet_percentage}%

Quality Score:
${data.quality_score}

Confidence Score:
${data.confidence_score}%

Contamination Risk:
${data.contamination_risk}

Batch Grade:
${data.batch_grade}

Estimated Value/kg:
$${data.estimated_value_per_kg}

Processing Recommendation:
${data.processing_recommendation}

Generated By:
RecycleVision AI
`;

    // CREATE BLOB
    const blob = new Blob(
      [report],
      {
        type: "text/plain",
      }
    );

    // CREATE URL
    const url =
      window.URL.createObjectURL(blob);

    // CREATE LINK
    const link =
      document.createElement("a");

    link.href = url;

    link.download = `${filename}.txt`;

    // DOWNLOAD
    document.body.appendChild(link);

    link.click();

    // CLEANUP
    document.body.removeChild(link);

    window.URL.revokeObjectURL(url);

    return true;

  } catch (error) {
    console.error(
      "Text export failed:",
      error
    );

    return false;
  }
}